---

- name: Search partuuid with blkid
  command: "blkid -s PARTUUID -o value /dev/sda2"
  register: v

- name: Compute partuuid
  set_fact: sys_partuuid={{ v.stdout }}
  when: v.rc == 0

- name: Mount efivars
  mount:
    name: "/sys/firmware/efi/efivars"
    src: "efivarfs" 
    fstype: "efivarfs"
    state: "mounted"

- name: Install bootloader
  command: bootctl install

- name: Install loader.conf
  copy: src=files/loader.conf dest=/boot/loader/loader.conf

- name: Install arch entry
  template: src=templates/arch_entry.j2 dest=/boot/loader/entries/arch.conf

- name: Install arch_lts entry
  template: src=templates/arch_lts_entry.j2 dest=/boot/loader/entries/arch-lts.conf

- name: Remove efivars
  mount:
    name: "/sys/firmware/efi/efivars"
    src: "efivarfs" 
    fstype: "efivarfs"
    state: "absent"
  ignore_errors: yes
