---
# tasks file for tlp
- name: install tlp
  pacman:
    name: [tlp, acpi_call]
    state: present
  become: true

- name: start tlp
  service:
    name: tlp
    state: started
    enabled: yes
  become: true
