---
# tasks file for etc
- name: visudo
  replace: >
    dest=/etc/sudoers
    regexp='^.*wheel.*NOPASSWD.*$'
    replace='%wheel ALL=(ALL) NOPASSWD:ALL'
    validate='visudo -cf %s'
  become: true

- name: pacman color
  replace:
    dest: /etc/pacman.conf
    regexp: '^.*Color.*$'
    replace: 'Color'
  become: true

- name: /etc/systemd/logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    state: present
    regexp: '#KillUserProcesses'
    line: 'KillUserProcesses=yes'
    backrefs: yes
  become: true

- name: /etc/systemd/system.conf
  lineinfile:
    path: /etc/systemd/system.conf
    state: present
    regexp: '#RuntimeWatchdogSec='
    line: 'RuntimeWatchdogSec=20'
    backrefs: yes
  become: true

- name: symlink /etc/resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  become: true
