---

- name: Install xapp
  pacman:
    name: '{{ packages }}'
    state: present
  become: true

  #- name: install urxvt-vtwheel
  #  copy:
  #    src: files/vtwheel
  #    dest: /usr/lib/urxvt/perl/vtwheel
  #  become: true

- name: setup Xresources
  copy:
    src: files/Xresources
    dest: '{{ ansible_user_dir }}/.Xresources'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: create configurations folders
  file:
    path: '{{ ansible_user_dir }}/{{ item }}'
    owner: '{{ username }}'
    group: users
    state: directory
    mode: 0755
  loop: [.mpv, .config/rofi]
  become: true
  become_user: '{{ username }}'

- name: config rofi
  copy:
    src: files/rofi
    dest: '{{ ansible_user_dir }}/.config/rofi/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: config mpv
  copy:
    src: files/mpv
    dest: '{{ ansible_user_dir }}/.mpv/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: config git
  copy:
    src: "files/{{ item }}"
    dest: '{{ ansible_user_dir }}/.{{ item }}'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'
  loop: [gitconfig, gitconfig.ignore]
