---
- hosts: localhost
  vars:
    username: '{{ ansible_user_id }}'

  pre_tasks:
    - fail:
        msg: "'username' or 'user_password' variable is not defined"
      when:
        - ansible_user_id == 'root'
        - username is undefined or user_password is undefined

    - debug:
        msg: "User is {{ username }}"

  roles:
    - { role: user, tags: user, when: user_password is defined }
    - { role: etc, tags: etc }
    - { role: aurutils, tags: aurutils }
    - { role: zsh, tags: zsh }
    - { role: nvim, tags: nvim }
    - { role: gpg, tags: gpg }
    - { role: smart, tags: smart }
    - { role: gnome, tags: gnome }
    - { role: networkmanager, tags: networkmanager }
    - { role: avahi, tags: avahi }
    - { role: tlp, tags: tlp }
    - { role: xserver, tags: xserver }
    - { role: nettool, tags: nettool }
    - { role: xapp, tags: xapp }
    - { role: i3, tags: i3 }
    - { role: vscode, tags: vscode }
