---

- hosts: localhost
  connection: local

  #  vars_prompt:
  #    - name: "user_password"
  #      prompt: "Enter the user password"
  #      private: yes

  pre_tasks:
    - fail:
        msg: "'username' or 'user_password' variable is not defined"
      when: username is undefined or user_password is undefined

    - debug:
        msg: "User {{ ansible_env.USER }}"

  roles:
    - { role: user, username: "{{ username }}", tags: user }
    - { role: base, tags: base }
    - { role: systool, tags: systool }
    - { role: nvim, tags: nvim }
    - { role: gpg, tags: gpg }
    - { role: nettool, tags: nettool }
    - { role: i3, tags: i3 }
    - { role: gnome, tags: gnome }
    - { role: smart, tags: smart }
    - { role: xserver, tags: xserver }
    - { role: xapp, tags: xapp }
      #- { role: aurutils, tags: aurutils }
      #- { role: dirty, tags: dirty }
