---

- hosts: localhost
  user: root

  vars_prompt:
    - name: "user_password"
      prompt: "Enter the user password"
      private: yes

  roles:
    - { role: user, username: "{{ username }}", tags: user }
    - { role: base, tags: base }
    - { role: systool, tags: systool }
    - { role: nvim, tags: nvim }
    - { role: nettool, tags: nettool }
    - { role: i3, tags: i3 }
    - { role: gnome, tags: gnome }      
    - { role: xserver, tags: xserver }
    - { role: xapp, tags: xapp }      
    - { role: aurutils, tags: aurutils }      
    - { role: dirty, tags: dirty }      
