---

- hosts: localhost

  #  vars_prompt:
  #    - name: "user_password"
  #      prompt: "Enter the user password"
  #      private: yes
  vars:
    username: "{{ ansible_env.USER }}"

  pre_tasks:
    - fail:
        msg: "'username' or 'user_password' variable is not defined"
      when:
        - ansible_env.USER == 'root'
        - username is undefined or user_password is undefined

    - debug:
        msg: "User is {{ username }}"

  roles:
    - { role: user, tags: user, when: user_password is defined }
    - { role: base, tags: base, become: true }
    - { role: zsh, tags: zsh, become: true }
    - { role: nvim, tags: nvim }
    - { role: gpg, tags: gpg }
    - { role: nettool, tags: nettool }
    - { role: i3, tags: i3 }
    - { role: gnome, tags: gnome }
    - { role: smart, tags: smart }
    - { role: xserver, tags: xserver }
    - { role: xapp, tags: xapp }
      #- { role: aurutils, tags: aurutils }
      #- { role: dirty, tags: dirty }
