---
# tasks file for gpg

- name: install package for Yubikey
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - pcsc-tools
    - ccid
    - libusb-compat
  become: true

- name: create .gnupg folder
  file:
    path: '{{ ansible_user_dir }}/.gnupg'
    owner: '{{ username }}'
    group: users
    state: directory
    mode: 0755
  become: true
  become_user: '{{ username }}'

- name: setup gpg-agent
  copy:
    src: files/gpg-agent.conf
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    owner: "{{ username }}"
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: enable pcscd
  service:
    name: pcscd
    enabled: yes
  become: true
