---
# tasks file for gnome

- name: Install gnome
  pacman:
    name: ['gnome', 'gnome-extra', 'pulseaudio-bluetooth', 'ttf-fira-code']
    state: present
  become: true

- name: enable gdm
  service: name=gdm enabled=yes
  become: true

- name: ensure dconf/user.d directory exists
  file:
    path: '{{ ansible_user_dir }}/.config/dconf/user.d'
    recurse: yes
    state: directory
  become: true
  become_user: '{{ username }}'

- name: add dconf files
  copy:
    src: 'files/{{ item }}'
    dest: '{{ ansible_user_dir }}/.config/dconf/user.d/{{ item }}'
    owner: '{{ username }}'
    group: users
    mode: 0644
  notify: dconf load
  become: true
  become_user: '{{ username }}'
  loop:
    - interface.conf
    - keyboard.conf
    - nautilus.conf
    - terminal.conf
    - touchpad.conf
    - mate.conf

- meta: flush_handlers

- name: ensure dconf/user.d directory exists
  file:
    path: '{{ ansible_user_dir }}/.config/gtk-3.0'
    recurse: yes
    state: directory
  become: true
  become_user: '{{ username }}'

- name: setup gtk-3.0
  copy:
    src: 'files/{{ item }}'
    dest: '{{ ansible_user_dir }}/.config/gtk-3.0/{{ item }}'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'
  loop: [bookmarks, settings.ini]

- name: setup gtk-2.0
  copy:
    src: 'files/gtkrc-2.0'
    dest: '{{ ansible_user_dir }}/.gtkrc-2.0'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'
