autoload -U compinit colors

compinit
colors

#TERM=rxvt-unicode-256color

## history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
#
#setopt append_history
#setopt inc_append_history
#setopt share_history
#setopt extended_history
#
#setopt hist_verify
#
#setopt hist_ignore_dups
#setopt hist_ignore_space
#
#setopt hist_fcntl_lock
#setopt hist_reduce_blanks
#
###
setopt autocd
setopt cd_able_vars

## glob
#setopt glob_dots

## prompt
PROMPT="%{$fg_bold[magenta]%}[%*] %(!.%{$fg_bold[red]%}.%{$fg_bold[green]%}%n@)%m %{$fg_bold[blue]%}%(!.%1~.%~) %(!.#.$)%{$reset_color%} "

## alias
setopt completealiases
alias grep='grep --color=always'
alias less='less -r'
alias ls='ls --classify --tabsize=0 --literal --color=auto --show-control-chars -h'
alias ll='ls -l'
alias la='ls -la'
alias ssh='TERM=xterm ssh'
alias sr='ssh -l root'
alias vim='nvim'

## export
eval `dircolors -b`
export EDITOR=/usr/bin/nvim
export GREP_COLORS='mt=1;31:sl=:cx=:fn=1;34:ln=1;35:bn=1;35:se=39'
export LESS='-R'
export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LESS_TERMCAP_md=$(tput bold; tput setaf 4) # blue
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 1) # red
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 2) # green
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

# export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
# unset SSH_AGENT_PID
# if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
#     export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
# fi

export WORDCHARS='*?_[]~=&;!#$%^(){}:'

## keybinding
typeset -A key

key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[PageUp]=${terminfo[kpp]}
key[PageDown]=${terminfo[knp]}

[[ -n "${key[Home]}"     ]]  && bindkey  "${key[Home]}"     beginning-of-line
[[ -n "${key[End]}"      ]]  && bindkey  "${key[End]}"      end-of-line
[[ -n "${key[Insert]}"   ]]  && bindkey  "${key[Insert]}"   overwrite-mode
[[ -n "${key[Delete]}"   ]]  && bindkey  "${key[Delete]}"   delete-char
[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"   history-beginning-search-backward
[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}" history-beginning-search-forward

bindkey '^[[1;5C' forward-word    # [Ctrl-RightArrow] - move forward one word
bindkey '^[[1;5D' backward-word   # [Ctrl-LeftArrow] - move backward one word

## completion
setopt always_to_end
setopt auto_list
setopt list_ambiguous
unsetopt rec_exact
setopt auto_menu

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:descriptions' format "%{$fg[cyan]%} %d%{$reset_color%}"

## case-insensitive,partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

## ignore completion functions (until the _ignored completer)
zstyle ':completion:*:functions' ignored-patterns '_*'

## kill command
zstyle ':completion:*:*:kill:*:processes' command "ps o start,pid,comm,pcpu -u $USER --forest"
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b)(?#)?([0-9][0-9].[0-9])*=36=36=31'

## offer indexes before parameters in subscripts
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

## insert all expansions for expand completer
zstyle ':completion:*:expand:*' tag-order all-expansions

zstyle ':completion:*' completer _complete _list _oldlist _expand _ignored _match _correct _approximate _prefix
zstyle ':completion:*:approximate:*' max-errors 'reply=( $(( ($#PREFIX+$#SUFFIX)/3 )) numeric )'

## zsh autosuggestions
if [ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]
then
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

## zsh-syntax-highlighting
if [ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]
then
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

  # Enable highlighters
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

  # Override highlighter colors
  ZSH_HIGHLIGHT_STYLES[default]=none
  ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=9
  ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=3
  ZSH_HIGHLIGHT_STYLES[alias]=fg=10
  ZSH_HIGHLIGHT_STYLES[builtin]=fg=10
  ZSH_HIGHLIGHT_STYLES[function]=fg=10
  ZSH_HIGHLIGHT_STYLES[command]=fg=10
  ZSH_HIGHLIGHT_STYLES[precommand]=fg=10
  ZSH_HIGHLIGHT_STYLES[commandseparator]=none
  ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=9
  ZSH_HIGHLIGHT_STYLES[path]=fg=12
  ZSH_HIGHLIGHT_STYLES[globbing]=fg=3
  ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=blue,underline
  ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=none
  ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=none
  ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
  ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=3
  ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=3
  ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=9
  ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=9
  ZSH_HIGHLIGHT_STYLES[assign]=none
fi
