---
# tasks file for mkinitcpio
- name: Comment initial HOOKS mkinitcpio.conf
  lineinfile:
    path: /etc/mkinitcpio.conf
    state: present
    regexp: '^(HOOKS=.*)$'
    line: '#\1'
    backrefs: yes
  become: true
  notify: mkinitcpio

- name: Update HOOKS mkinitcpio.conf
  lineinfile:
    path: /etc/mkinitcpio.conf
    state: present
    insertafter: '^#HOOKS='
    line: 'HOOKS=(base systemd autodetect keyboard sd-vconsole modconf block sd-encrypt sd-lvm2 filesystems fsck)'
  become: true
  notify: mkinitcpio

- name: Update MODULES mkinitcpio.conf
  lineinfile:
    path: /etc/mkinitcpio.conf
    state: present
    regexp: '^MODULES='
    line: 'MODULES="i915"'
  become: true
  notify: mkinitcpio
