---
# handlers file for gnome
- name: dconf load
  shell: 'cat {{ ansible_user_dir }}/.config/dconf/user.d/* | dbus-launch dconf load /'
  args:
    executable: /bin/bash
  become: true
  become_user: '{{ username }}'
