---
# - name: Mount swap partition
#   mount:
#     path: swap
#     src: /dev/vg.main/swap
#     fstype: swap
#     opts: sw
#     state: mounted

- name: Active swap volume
  command: swapon /dev/vg.main/swap

- name: Mount root volume
  mount:
    path: /mnt
    src: /dev/vg.main/root
    fstype: ext4
    state: mounted

- name: Mount boot partition ({{ uefi_part_dev }})
  mount:
    name: /mnt/boot
    src: "{{ uefi_part_dev }}"
    fstype: vfat
    state: mounted
