---
# tasks file for networkmanager
- name: Install networkmanager
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - networkmanager
    - network-manager-applet

- name: Start networkmanager service
  service:
    name: NetworkManager
    state: started
    enabled: yes
