---
# tasks file for networkmanager
- name: Install networkmanager
  pacman:
    name: [networkmanager, network-manager-applet, iwd]
    state: present
  become: true

- name: Start networkmanager service
  service:
    name: NetworkManager
    enabled: yes
  become: true