---
# tasks file for networkmanager
- name: Install networkmanager
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - networkmanager
    - network-manager-applet
  become: true

- name: Start networkmanager service
  service:
    name: NetworkManager
    enabled: yes
  become: true
