---

- name: pacstrap on host
  command: "pacstrap /mnt base base-devel btrfs-progs ansible git intel-ucode linux-lts"
  when: ansible_virtualization_role == 'host'

- name: pacstrap on guest
  command: "pacstrap -c /mnt base base-devel btrfs-progs ansible git intel-ucode linux-lts"
  when: ansible_virtualization_role == 'guest'
