---
- name: pacstrap on host
  command: "pacstrap /mnt base base-devel ansible intel-ucode linux-lts wpa_supplicant"
  when: ansible_virtualization_role == 'host'

- block:
  - name: pacstrap on guest
    command: "pacstrap -c /mnt base base-devel ansible intel-ucode linux-lts openssh spice-vdagent"

  - name: Create ssh directory
    file: path=/mnt/root/.ssh state=directory

  - name: Copy ssh authorized_keys
    copy:
      src: "/root/.ssh/authorized_keys"
      dest: "/mnt/root/.ssh/authorized_keys"
      remote_src: true
  when: ansible_virtualization_role == 'guest'

  #- name: Refresh pacman gpg keys
  #command: pacman-key --refresh-keys --config /mnt/etc/pacman.conf --gpgdir /mnt/etc/pacman.d/gnupg
