---

- name: install xorg driver
  pacman:
    name: [vulkan-intel, intel-media-driver, xf86-input-libinput]
    state: present
  become: true

- name: Create i915.conf
  lineinfile:
    path: /etc/modprobe.d/i915.conf
    line: 'options i915 enable_guc=2 enable_fbc=1 fastboot=1'
    create: yes
  become: true 

- name: ensure xorg.conf.d directory exists
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
  become: true

- name: Create {{ item }}
  copy:
    src: "files/{{ item }}"
    dest: "/etc/X11/xorg.conf.d/{{ item }}"
  become: true
  loop:
    - 00-keyboard.conf
    - 10-monitor.conf
    - 10-mouse.conf
    - 30-touchpad.conf
