---

- name: install neovim
  pacman:
    name: neovim
    state: present

- name: ensure nvim directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - 'colors'
    - 'autoload'  

- name: install config file
  copy:
    src: files/init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    owner: "{{ ansible_env.USER }}"
    group: users
    mode: 0644

- name: install colors scheme
  copy:
    src: files/molokai.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/colors/molokai.vim"
    owner: "{{ ansible_env.USER }}"
    group: users
    mode: 0644

- name: install vim-plug
  copy:
    src: files/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim"
    owner: "{{ ansible_env.USER }}"
    group: users
    mode: 0644
