---
- name: install neovim
  pacman:
    name: neovim
    state: present
  become: true

- name: ensure nvim directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/nvim/{{ item }}"
    recurse: yes
    owner: "{{ username }}"
    group: users
    state: directory
  loop: [colors, autoload]
  become: true
  become_user: '{{ username }}'

- name: install config file
  copy:
    src: files/init.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: install colors scheme
  copy:
    src: files/molokai.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/colors/molokai.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: install vim-plug
  copy:
    src: files/plug.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/autoload/plug.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'
