---

- name: install neovim
  pacman:
    name: neovim
    state: present
  become: yes

- name: ensure nvim directory exists
  file:
    path: "/home/{{ username }}/.config/nvim/{{ item }}"
    recurse: yes
    owner: "{{ username }}"
    group: users
    state: directory
  with_items:
    - 'colors'
    - 'autoload'

- name: install config file
  copy:
    src: files/init.vim
    dest: "/home/{{ username }}/.config/nvim/init.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644

- name: install colors scheme
  copy:
    src: files/molokai.vim
    dest: "/home/{{ username }}/.config/nvim/colors/molokai.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644

- name: install vim-plug
  copy:
    src: files/plug.vim
    dest: "/home/{{ username }}/.config/nvim/autoload/plug.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644
