---

- name: build neovim-airline
  command: 'aur sync -c --no-view {{ item }}'
  args:
    creates: '/var/cache/pacman/custom/{{ item }}*'
  become: true
  become_user: '{{ username }}'
  loop:
    - neovim-airline
    - neovim-airline-themes

- name: install neovim
  pacman:
    name: [neovim, neovim-airline, neovim-airline-themes]
    state: present
    update_cache: yes
  become: true

- name: install config file
  copy:
    src: files/koaxiel.vim
    dest: '/usr/share/nvim/koaxiel.vim'
    mode: 0644
  become: true

- name: update sysinit.vim
  lineinfile:
    dest: /etc/xdg/nvim/sysinit.vim
    line: 'source /usr/share/nvim/koaxiel.vim'
  become: true

- name: install colors scheme
  copy:
    src: files/molokai.vim
    dest: "/usr/share/nvim/runtime/colors/molokai.vim"
    mode: 0644
  become: true
