---

- name: install neovim
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim

- name: install config file
  copy:
    src: files/init.vim
    dest: "/home/{{ username }}/.config/nvim/init.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644

- name: install colors scheme
  copy:
    src: files/molokai.vim
    dest: "/home/{{ username }}/.config/nvim/colors/molokai.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644

- name: install vim-plug
  copy:
    src: files/plug.vim
    dest: "/home/{{ username }}/.config/nvim/autoload/plug.vim"
    owner: "{{ username }}"
    group: users
    mode: 0644
