---

- hosts: localhost
  user: root
  connection: local
  roles:
     - { role: partitioning, tags: partioning }
     - { role: mounting, tags: mounting }
     - { role: pacstrap, tags: pacstrap }

  post_tasks:
        - name: mount pseudo file systems 
          mount: 
            src: "/{{ item }}"
            name: "/mnt/{{ item }}"
            fstype: "{{ 'proc' if item == 'proc' else 'bind' }}"
            state: "mounted"
            opts: "rbind"
          with_items:
            - proc
            - sys
            - dev
            - run
          tags: chroot

- hosts: /mnt
  user: root
  connection: chroot

  vars_prompt:
    - name: "root_password"
      prompt: "Enter the root password"
      private: yes

  roles:
   - { role: locale, tags: locale }
   - { role: time, tags: time }
   - { role: bootloader, tags: bootloader }
   - { role: fstab, tags: fstab }
   - { role: hostname, tags: hostname }
   - { role: network, tags: network }

  tasks:
    - name: set root password
      user: name=root password={{ root_password |password_hash('sha512') }}
      tags: root

#  post_tasks:
#    - name: umount pseudo file systems
#      mount: 
#        src: "/{{ item }}"
#        name: "/mnt/{{ item }}"
#        fstype: "{{ 'proc' if item == 'proc' else 'bind' }}" 
#        state: "unmounted"
#        opts: "rbind"
#      with_items:
#        - proc
#        - sys
#        - dev
#        - run
#      tags: umount
#      connection: local
