---
- hosts: localhost
  user: root
  connection: local

  pre_tasks:
  - fail:
      msg: "'hostname' or 'root_password' variable is not defined"
    when: hostname is undefined or root_password is undefined

  roles:
     - { role: partitioning, tags: partioning }
     - { role: mounting, tags: mounting }
     - { role: pacstrap, tags: pacstrap }

  post_tasks:
  - name: Mount pseudo file systems
    mount:
      src: "/{{ item }}"
      name: "/mnt/{{ item }}"
      fstype: "{{ 'proc' if item == 'proc' else 'bind' }}"
      state: "mounted"
      opts: "rbind"
    with_items:
      - proc
      - sys
      - dev
      - run

  - name: Mount efivars
    mount:
      name: "/sys/firmware/efi/efivars"
      src: "efivarfs"
      fstype: "efivarfs"
      state: "mounted"

- hosts: /mnt
  user: root
  connection: chroot

  roles:
   - { role: locale, tags: locale }
   - { role: systemd-firstboot, tags: systemd-firstboot }
   - { role: snapper, tags: snapper }
   - { role: fstab, tags: fstab }
   - { role: bootloader, tags: bootloader }
   - { role: network, tags: network }
     # watchdog + installer dans la VM

  tasks:
  - name: Set root's password
    user: name=root password={{ root_password |password_hash('sha512') }}
    tags: root

  - block:
    - name: Enable sshd
      #service: name=sshd enabled=yes
      command: systemctl enable sshd.service
      args:
        creates: /etc/systemd/system/multi-user.target.wants/sshd.service

    - name: Enable dhcpcd
      #service: name=dhcpcd enabled=yes
      command: systemctl enable dhcpcd.service
      args:
        creates: /etc/systemd/system/multi-user.target.wants/dhcpcd.service

    when: ansible_virtualization_role == 'guest'
  #- hosts: localhost
  #  user: root
  #  connection: local
  #
  #  tasks:
  #  post_tasks:
  #    - name: umount pseudo file systems
  #      mount:
  #        src: "/{{ item }}"
  #        name: "/mnt/{{ item }}"
  #        fstype: "{{ 'proc' if item == 'proc' else 'bind' }}"
  #        state: "unmounted"
  #        opts: "rbind"
  #      with_items:
  #        - proc
  #        - sys
  #        - dev
  #        - run
  #      tags: unchroot
