---
- name: "check if {{ disk_dev }} exists"
  stat: "path={{ disk_dev }}"
  register: disk

- fail:
    msg: "{{ disk_dev }} isn't defined (path doesn't exist)"
  when: not disk.stat.exists

- name: "Unmount {{ disk_dev }} partitions if existing"
  command: "umount -fl {{ item.device }}"
  with_items:
    - "{{ ansible_mounts }}"
  when: "disk_dev in item.device"
  become: yes

- name: "Zeroize {{ disk_dev }}"
  shell: "blkdiscard {{ disk_dev }})"
  become: yes

- name: "Partitioning {{ disk_dev }}"
  command: "{{ item }}"
  with_items:
    - "sgdisk -Z {{ disk_dev }}"
    - "partprobe {{ disk_dev }}"
    - "parted -s {{ disk_dev }} mklabel gpt"
    - "parted -s {{ disk_dev }} mkpart primary fat32 1MiB 513MiB"
    - "parted -s {{ disk_dev }} mkpart primary btrfs 513MiB 100%"
    - "parted -s {{ disk_dev }} set 1 boot on"
  register: partition
  become: yes

- name: "Fail if return code is not 0"
  fail:
    msg: "The command ({{ item.cmd }}) did not have a 0 return code"
  when: item.rc != 0
  with_items: "{{partition.results}}"

- name: "Formate boot partition"
  command: "mkfs.fat -F32 -n EFI {{ disk_dev }}1"

- name: "Formate system partition"
  filesystem:
    fstype: btrfs
    opts: "-L System"
    dev : "{{ disk_dev }}2"
