---

- name: install i3
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - i3
    - polkit-gnome
  become: true

- name: create .i3 folder
  file:
    path: '{{ item }}'
    owner: '{{ username }}'
    group: users
    state: directory
    mode: 0755
  with_items:
    - '{{ ansible_user_dir }}/.config/i3'
    - '{{ ansible_user_dir }}/.config/i3status'
  become: true
  become_user: '{{ username }}'

- name: configure i3
  copy:
    src: files/config
    dest: '{{ ansible_user_dir }}/.config/i3/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: configure i3status
  copy:
    src: files/i3status.conf
    dest: '{{ ansible_user_dir }}/.config/i3status/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: Build xsettingsd-git
  command: aursync -cu --no-view xsettingsd-git
  args:
    creates: '{{ ansible_user_dir }}/.cache/aursync/xsettingsd-git/PKGBUILD'
  become: true
  become_user: '{{ username }}'

- name: Install xsettingsd-git
  pacman:
    name: xsettingsd-git
    state: present
    update: yes
