---

- name: install i3
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - i3
    - polkit-gnome
  become: true

- name: create .i3 folder
  file:
    path: '{{ item }}'
    owner: '{{ username }}'
    group: users
    state: directory
    mode: 0755
  with_items:
    - '{{ ansible_user_dir }}/.config/i3'
    - '{{ ansible_user_dir }}/.config/i3status'
  become: true
  become_user: '{{ username }}'

- name: configure i3
  copy:
    src: files/config
    dest: '{{ ansible_user_dir }}/.config/i3/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: configure i3status
  copy:
    src: files/i3status.conf
    dest: '{{ ansible_user_dir }}/.config/i3status/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: Build xsettingsd-git
  command: 'aursync -c --no-view {{ item }}'
  args:
    creates: '/var/cache/pacman/custom/{{ item }}*'
  become: true
  become_user: '{{ username }}'
  with_items:
    - xsettingsd-git

- name: Build paper-icon-theme-git
  command: 'aursync -c --no-view {{ item }}'
  args:
    creates: '/var/cache/pacman/custom/{{ item }}*'
  become: true
  become_user: '{{ username }}'
  with_items:
    - paper-icon-theme-git

- name: Build adapta-gtk-theme
  command: 'aursync -c --no-view {{ item }}'
  args:
    creates: '/var/cache/pacman/custom/{{ item }}*'
  become: true
  become_user: '{{ username }}'
  with_items:
    - adapta-gtk-theme

- name: Build py3status
  command: 'aursync -c --no-view {{ item }}'
  args:
    creates: '/var/cache/pacman/custom/{{ item }}*'
  become: true
  become_user: '{{ username }}'
  with_items:
    - py3status

- name: Install package
  pacman:
    name: '{{ item }}'
    state: present
    update_cache: yes
  become: true
  with_items:
    - xsettingsd-git
    - paper-icon-theme-git
    - adapta-gtk-theme
    - py3status

- name: configure xsettingsd
  copy:
    src: files/xsettingsd
    dest: '{{ ansible_user_dir }}/.xsettingsd'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

