---

- name: install i3
  pacman:
    name: '{{ packages }}'
    state: present
  become: true

- name: create .i3 folder
  file:
    path: '{{ item }}'
    owner: '{{ username }}'
    group: users
    state: directory
    mode: 0755
  loop:
    - '{{ ansible_user_dir }}/.config/i3'
    - '{{ ansible_user_dir }}/.config/i3status'
    - '{{ ansible_user_dir }}/.config/environment.d'
  become: true
  become_user: '{{ username }}'

- name: configure i3
  copy:
    src: files/config
    dest: '{{ ansible_user_dir }}/.config/i3/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: configure i3status
  copy:
    src: files/i3status.conf
    dest: '{{ ansible_user_dir }}/.config/i3status/config'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: configure environment
  copy:
    src: files/i3.conf
    dest: '{{ ansible_user_dir }}/.config/environment.d/i3.conf'
    owner: '{{ username }}'
    group: users
    mode: 0644
  become: true
  become_user: '{{ username }}'

- name: Build paper-icon-theme
  command: 'aur sync -c --no-view {{ item }}'
  args:
    creates: '/var/cache/pacman/custom/{{ item }}*'
  become: true
  become_user: '{{ username }}'
  with_items:
    - paper-icon-theme

- name: Install package
  pacman:
    name: 'paper-icon-theme'
    state: present
    update_cache: yes
  become: true
