---

- name: install yaourt
  pacman: name=yaourt state=present

- name: install aurtils
  command: "yaourt -S aurutils --noconfirm"
  become: yes
  become_user: "{{ username }}"

- name: "repose"
  shell: "cd /home/packages && repose -fv custom" 
  become: yes 
  become_user: "{{ username }}"

- name: "pacman update"
  pacman: update_cache=yes force=yes

- name: "pacman upgrade"
  pacman: update_cache=yes upgrade=yes

- name: compile aur package
  command: "aursync -ck aurutils adapta-gtk-theme paper-icon-theme-git xsettingsd-git"
  become: yes
  become_user: "{{ username }}"
  register: command_result
  failed_when: "command_result.rc > 1"
  changed_when: "command_result.rc != 1"

- name: remove aurutils and yaourt
  pacman: name=aurutils,yaourt state=absent recurse=yes

- name: install aur package
  pacman: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - aurutils
    - adapta-gtk-theme
    - paper-icon-theme-git
    - xsettingsd-git
